name: Badminton Slot Tracker

on:
  #schedule:
    #- cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:
    inputs:
      is_manual:
        description: 'Triggered manually via Telegram'
        required: false
        default: 'false'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TARGET_WEEKDAY: ${{ vars.TARGET_WEEKDAY }}
          TARGET_TIME: ${{ vars.TARGET_TIME }}
          IS_MANUAL: ${{ inputs.is_manual }}
        run: python scraper.py
