name: Badminton Slot Tracker

on:
  schedule:
    #- cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:         # Allows triggering on-demand via API or UI

jobs:
  check-slots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TARGET_WEEKDAY: ${{ vars.TARGET_WEEKDAY }}
          TARGET_TIME: ${{ vars.TARGET_TIME }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python scraper.py
